Update action.yml

diff --git a/.github/actions/docker-sync/action.yml b/.github/actions/docker-sync/action.yml
--- a/.github/actions/docker-sync/action.yml
+++ b/.github/actions/docker-sync/action.yml
@@ -16,6 +16,10 @@ inputs:
     description: The maximum number of image tags to sync
     required: false
     default: '10'
+  max-errors:
+    description: maximimum number of errors to tolerate before failure
+    required: false
+    default: '5'
 
 runs:
   using: composite
@@ -25,22 +29,29 @@ runs:
   - name: Sync images
     shell: bash
     run: |
+      #!/usr/bin/env bash
       set -ux -o pipefail
       skopeo --version
 
       VERSIONS="$(skopeo list-tags docker://${{ inputs.source }} | jq -r '.Tags[] | scan("latest|stable|.*[0-9]+\\.[0-9]+\\.[0-9]+.*")' | sort --version-sort | uniq | tail -n ${{ inputs.max-tags }})"
+
+      error_count=0
 
       echo "${VERSIONS}" | while read version ; do
 
           if [ "$version" = "" ]; then
               break
           fi
+          if [ "$error_count" -gt "${{ imputs.max-errors }}" ]; then
+              echo "::error:: Errors copying images from ${{ inputs.source }} exceeded the maximum allowed."
+              exit 1
+          fi
 
           if [ "$version" = "latest" ] || [ "$version" = "stable" ]; then
               # Always copy "latest" and "stable"
               regctl image copy \
                   ${{ inputs.source }}:$version \
-                  ${{ inputs.destination }}:$version
+                  ${{ inputs.destination }}:$version || ((error_count++))
               continue
           fi
 
@@ -48,7 +59,7 @@ runs:
           skopeo inspect docker://${{ inputs.destination }}:$version >/dev/null 2>&1 || \
           regctl image copy \
               ${{ inputs.source }}:$version \
-              ${{ inputs.destination }}:$version
+              ${{ inputs.destination }}:$version || ((error_count++))
 
       done
 
